//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// ------------------- Function Prototypes --------------------

int32_t decrypt(int32_t a1);
int32_t test(int32_t a1, int32_t a2);

// --------------------- Global Variables ---------------------

int32_t g1;
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x8048660 - 0x8048747
int32_t decrypt(int32_t a1) {
    int32_t v1 = __readgsdword(20); // 0x8048668
    int32_t v2 = 0x757c7d51; // bp-33, 0x8048673
    int32_t v3 = 0; // bp-80, 0x8048693
    int32_t v4 = &v2; // 0x80486b0
    bool v5; // 0x8048660
    int32_t v6 = v5 ? -1 : 1;
    int32_t v7 = -1; // 0x80486b2
    int32_t v8 = v4; // 0x80486b2
    int32_t v9 = 0; // 0x80486b2
    while (v7 != 0) {
        int32_t v10 = v8;
        v7--;
        v8 = v10 + v6;
        v9 = v7;
        if (*(char *)v10 == 0) {
            // break -> 
            break;
        }
        v9 = 0;
    }
    int32_t v11 = -2 - v9; // 0x80486b8
    if (v11 != 0) {
        int32_t v12 = 0; // 0x80486e1
        char * v13 = (char *)(v12 + v4); // 0x80486cd
        *v13 = *v13 ^ (char)a1;
        v12++;
        while (v12 != v11) {
            // 0x80486c7
            v13 = (char *)(v12 + v4);
            *v13 = *v13 ^ (char)a1;
            v12++;
        }
    }
    int32_t v14 = (int32_t)"Congratulations!"; // 0x8048660
    int32_t v15 = v4; // 0x8048660
    int32_t v16 = 17; // 0x8048700
    unsigned char v17 = *(char *)v15; // 0x8048700
    char v18 = *(char *)v14; // 0x8048700
    char v19 = v18; // 0x8048700
    bool v20 = false; // 0x8048700
    while (v17 == v18) {
        v16--;
        v14 += v6;
        v15 += v6;
        v19 = v17;
        v20 = true;
        if (v16 == 0) {
            // break -> 
            break;
        }
        v17 = *(char *)v15;
        v18 = *(char *)v14;
        v19 = v18;
        v20 = false;
    }
    unsigned char v21 = v19;
    int32_t * v22 = (int32_t *)((int32_t)&v3 + 4);
    int32_t puts_rc; // 0x8048660
    if ((v17 >= v21 && !v20) != v17 < v21) {
        // 0x8048723
        *v22 = (int32_t)"\nInvalid Password";
        puts_rc = puts((char *)&g2);
    } else {
        // 0x8048715
        *v22 = (int32_t)"/bin/sh";
        puts_rc = system((char *)&g2);
    }
    int32_t result = puts_rc; // 0x8048739
    if (v1 != __readgsdword(20)) {
        // 0x804873b
        __stack_chk_fail();
        result = &g2;
    }
    // 0x8048740
    return result;
}

// Address range: 0x8048747 - 0x804885a
int32_t test(int32_t a1, int32_t a2) {
    int32_t v1 = a2 - a1; // 0x8048755
    g1 = v1;
    int32_t result; // 0x8048747
    switch (v1) {
        case 1: {
            // 0x8048775
            result = decrypt(1);
            // break -> 0x8048858
            break;
        }
        case 2: {
            // 0x8048785
            result = decrypt(2);
            // break -> 0x8048858
            break;
        }
        case 3: {
            // 0x8048795
            result = decrypt(3);
            // break -> 0x8048858
            break;
        }
        case 4: {
            // 0x80487a5
            result = decrypt(4);
            // break -> 0x8048858
            break;
        }
        case 5: {
            // 0x80487b5
            result = decrypt(5);
            // break -> 0x8048858
            break;
        }
        case 6: {
            // 0x80487c5
            result = decrypt(6);
            // break -> 0x8048858
            break;
        }
        case 7: {
            // 0x80487d5
            result = decrypt(7);
            // break -> 0x8048858
            break;
        }
        case 8: {
            // 0x80487e2
            result = decrypt(8);
            // break -> 0x8048858
            break;
        }
        case 9: {
            // 0x80487ef
            result = decrypt(9);
            // break -> 0x8048858
            break;
        }
        case 16: {
            // 0x80487fc
            result = decrypt(16);
            // break -> 0x8048858
            break;
        }
        case 17: {
            // 0x8048809
            result = decrypt(17);
            // break -> 0x8048858
            break;
        }
        case 18: {
            // 0x8048816
            result = decrypt(18);
            // break -> 0x8048858
            break;
        }
        case 19: {
            // 0x8048823
            result = decrypt(19);
            // break -> 0x8048858
            break;
        }
        case 20: {
            // 0x8048830
            result = decrypt(20);
            // break -> 0x8048858
            break;
        }
        case 21: {
            // 0x804883d
            result = decrypt(21);
            // break -> 0x8048858
            break;
        }
        default: {
            // 0x804884a
            result = decrypt(rand());
            // break -> 0x8048858
            break;
        }
    }
    // 0x8048858
    return result;
}

// Address range: 0x804885a - 0x80488e1
int main(int argc, char ** argv) {
    // 0x804885a
    int32_t t; // bp-52, 0x804885a
    int32_t v1 = &t; // 0x8048863
    int32_t * v2 = (int32_t *)(v1 + 4); // 0x804886c
    *v2 = 0;
    *v2 = time((int32_t *)t);
    srand((int32_t)&g2);
    *v2 = (int32_t)"***********************************";
    puts((char *)&g2);
    *v2 = (int32_t)"*\t\tlevel03\t\t**";
    puts((char *)&g2);
    *v2 = (int32_t)"***********************************";
    puts((char *)&g2);
    *v2 = (int32_t)"Password:";
    printf((char *)&g2);
    int32_t v3 = v1 + 32; // 0x80488b6
    int32_t * v4 = (int32_t *)(v1 + 8); // 0x80488ba
    *v4 = v3;
    *v2 = (int32_t)"%d";
    scanf((char *)&g2);
    *v4 = 0x1337d00d;
    *v2 = *(int32_t *)v3;
    test((int32_t)&g2, (int32_t)&g2);
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected functions: 3


