/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
int sub_8048350();
// int printf(const char *format, ...);
// char *fgets(char *s, int n, FILE *stream);
// int puts(const char *s);
// int __gmon_start__(void); weak
// int __libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// void __usercall __noreturn start(int a1@<eax>, void (*a2)()@<edx>);
void _do_global_dtors_aux();
int frame_dummy();
_BOOL4 verify_user_name();
_BOOL4 __cdecl verify_user_pass(const void *a1);
int __cdecl main(int argc, const char **argv, const char **envp);
void _libc_csu_fini(); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
int _CTOR_LIST__[] = { -1 }; // weak
int _DTOR_LIST__[] = { -1 }; // weak
int _DTOR_END__ = 0; // weak
int _JCR_LIST__ = 0; // weak
Elf32_Dyn *GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
int (*dword_8049FFC)(void) = NULL; // weak
FILE *stdin; // idb
char completed_6159; // weak
int dtor_idx_6161; // weak
char a_user_name[100]; // idb
// extern _UNKNOWN _gmon_start__; weak


//----- (08048318) --------------------------------------------------------
// Alternative name is '_init'
void (*init_proc())(void)
{
  if ( &_gmon_start__ )
    __gmon_start__();
  frame_dummy();
  return _do_global_ctors_aux();
}
// 8048390: using guessed type int __gmon_start__(void);

//----- (08048350) --------------------------------------------------------
int sub_8048350()
{
  return dword_8049FFC();
}
// 8049FFC: using guessed type int (*dword_8049FFC)(void);

//----- (080483B0) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1@<eax>, void (*a2)()@<edx>)
{
  int v2; // esi
  int v3; // [esp-4h] [ebp-4h] BYREF
  char *retaddr; // [esp+0h] [ebp+0h] BYREF

  v2 = v3;
  v3 = a1;
  __libc_start_main(
    (int (*)(int, char **, char **))main,
    v2,
    &retaddr,
    (void (*)())_libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 80483B3: positive sp value 4 has been found

//----- (080483E0) --------------------------------------------------------
void _do_global_dtors_aux()
{
  int v0; // eax
  unsigned int i; // ebx

  if ( !completed_6159 )
  {
    v0 = dtor_idx_6161;
    for ( i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6161 < i; v0 = dtor_idx_6161 )
    {
      dtor_idx_6161 = v0 + 1;
      ((void (*)(void))_DTOR_LIST__[v0 + 1])();
    }
    completed_6159 = 1;
  }
}
// 8049F1C: using guessed type int _DTOR_LIST__[];
// 8049F20: using guessed type int _DTOR_END__;
// 804A024: using guessed type char completed_6159;
// 804A028: using guessed type int dtor_idx_6161;

//----- (08048440) --------------------------------------------------------
int frame_dummy()
{
  int result; // eax

  result = _JCR_LIST__;
  if ( _JCR_LIST__ )
    return 0;
  return result;
}
// 8049F24: using guessed type int _JCR_LIST__;

//----- (08048464) --------------------------------------------------------
_BOOL4 verify_user_name()
{
  puts("verifying username....\n");
  return memcmp(a_user_name, "dat_wil", 7u) != 0;
}

//----- (080484A3) --------------------------------------------------------
_BOOL4 __cdecl verify_user_pass(const void *a1)
{
  return memcmp(a1, "admin", 5u) != 0;
}

//----- (080484D0) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  char s[64]; // [esp+1Ch] [ebp-4Ch] BYREF
  _BOOL4 v5; // [esp+5Ch] [ebp-Ch]

  memset(s, 0, sizeof(s));
  v5 = 0;
  puts("********* ADMIN LOGIN PROMPT *********");
  printf("Enter Username: ");
  fgets(a_user_name, 256, stdin);
  v5 = verify_user_name();
  if ( v5 )
  {
    puts("nope, incorrect username...\n");
  }
  else
  {
    puts("Enter Password: ");
    fgets(s, 100, stdin);
    v5 = verify_user_pass(s);
    puts("nope, incorrect password...\n");
  }
  return 1;
}

//----- (080485C0) --------------------------------------------------------
void __cdecl _libc_csu_init(int a1, int a2, int a3)
{
  int v3; // edi
  int i; // esi

  init_proc();
  v3 = (134520820 - (int)&GLOBAL_OFFSET_TABLE_) >> 2;
  if ( v3 )
  {
    for ( i = 0; i != v3; ++i )
      ((void (__cdecl *)(int, int, int))_CTOR_LIST__[i])(a1, a2, a3);
  }
}
// 8049F14: using guessed type int _CTOR_LIST__[];
// 8049FF4: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (08048640) --------------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
  void (*result)(void); // eax
  void (**v1)(void); // ebx

  result = (void (*)(void))_CTOR_LIST__[0];
  if ( _CTOR_LIST__[0] != -1 )
  {
    v1 = (void (**)(void))_CTOR_LIST__;
    do
    {
      --v1;
      result();
      result = *v1;
    }
    while ( *v1 != (void (*)(void))-1 );
  }
  return result;
}
// 8049F14: using guessed type int _CTOR_LIST__[];

//----- (0804866C) --------------------------------------------------------
// Alternative name is '_fini'
void term_proc()
{
  _do_global_dtors_aux();
}

// nfuncs=23 queued=11 decompiled=11 lumina nreq=0 worse=0 better=0
// ALL OK, 11 function(s) have been successfully decompiled
