//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/prctl.h>
#include <sys/wait.h>
#include <unistd.h>

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t ptrace(int32_t a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x80486c8 - 0x8048826
int main(int argc, char ** argv) {
    int32_t pid = fork(); // 0x80486d6
    int32_t str; // bp-160, 0x80486c8
    __asm_rep_stosd_memset((char *)&str, 0, 32);
    int32_t stat_loc = 0; // bp-164, 0x8048701
    if (pid == 0) {
        // 0x8048713
        prctl(PR_SET_PDEATHSIG, 1, (int32_t)&g1, (int32_t)&g1, (int32_t)&g1);
        ptrace(0);
        puts("Give me some shellcode, k");
        gets((char *)&str);
        // 0x804881a
        return 0;
    }
    wait((int32_t)&stat_loc);
    // 0x8048769
    while (stat_loc % 128 != 0) {
        char v1 = (char)stat_loc % 128 + 1; // 0x80487a6
        if (v1 >= 2 && v1 >= 0) {
            // break -> 0x80487ac
            break;
        }
        // 0x80487ba
        if (ptrace(3) == 11) {
            // 0x80487f6
            puts("no exec() for you");
            kill(pid, SIGKILL);
            return 0;
        }
        wait((int32_t)&stat_loc);
    }
    // 0x80487ac
    puts("child is exiting...");
    // 0x804881a
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected functions: 1

